### ISSUE TITLE
Project URL

### ISSUE THREAD

**Issue by SeriousM** [ttrider/VSExtensionsImportExport#3]
Hi again,

I know it might sound trivial, but please set the url of the repository to the vs gallery url `https://visualstudiogallery.msdn.microsoft.com/a6a60f27-cf56-48c8-8ee0-b631716dd11c`.

![image](https://cloud.githubusercontent.com/assets/462013/12816702/39db4112-cb4e-11e5-95fa-1b6962093101.png)

Thank you!

**Comment by ttrider** [comment]
Done!

Thank You
